version: '3.8'

services:
  frontend:
    build: .
    ports:
      - "8080:80"
    depends_on:
      - backend
    networks:
      - port-manager-network

  backend:
    build: ./backend
    ports:
      - "3001:3001"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - port-manager-network
    environment:
      - NODE_ENV=production

networks:
  port-manager-network:
    driver: bridge